#READ THE EXPLANATION CAREFULLY BEFORE STARTING THE WORKFLOW#

#This workflow works for ONLY 1 tumor and 1 normal sample coming from the same patient and it contains the steps starting from mapping to variant calling.

#Before starting, please locate the paths of: 

#1-)tumor and Blood controls of your patients to this config file in 'Samples and Patients' section
    #There are 3 things to consider in #Samples and Patients section:
        #For samples, the keys must be in the pattern of "PatientX_Tumor1" & "PatientX_Blood1" e.g. Patient1_Tumor1, Patient1_Blood1, Patient2_Tumor1..etc.
        #For patients, the keys must be in the pattern of "PatientX" e.g. Patient1, Patient2 ..etc.
        #p.s. do not forget to type the n_of_patients! 

#2-)your annotation files in 'Annotation files' section 

#3-)of the tools and make your changes on their options

#for questions please contact: hamdiyeuzuner@gmail.com

#Samples and Patients#
samples:
    Patient1_Tumor1: /home/hamdiye/Documents/SNAKEMAKE/VC/data/Tumor1
    Patient1_Blood1: /home/hamdiye/Documents/SNAKEMAKE/VC/data/Blood1

#Patients
n_of_patients: 1
patients:
    Patient1: /home/hamdiye/Documents/SNAKEMAKE/VC/recal/Patient1

#Annotation files#
genome: data/genome/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
germline: data/known_sites/af-only-gnomad.hg38.vcf.gz
Mills: data/known_sites/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
dbSNP: data/known_sites/ALL_20141222.dbSNP142_human_GRCh38.snps.vcf.gz

#Tool options
PathToPicard: /home/hamdiye/Documents/Software/picard-tools-1.131
bwa_mem: 10
mutect2: 10
mutect2_java_opt: "--java-options '-Xmx14G'"
